#! /usr/bin/env python
# -*- python -*-

"""Fit a point source to a generous interpretation of a specified
box. See box-region for a general description of the 'box' scripts.

Usage: box-fitpoint <boxfile> <image> <boxnum>

<boxnum> is number of the box for which to do the fit, starting at
1. So each box's number is its line number in the file as reported
by a text editor.
"""

import sys
import miriad, mirexec

miriad.basicTrace ()

## quickutil: words
#- snippet: words.py
#- date: 2012 Feb 27
#- SHA1: c571563028e9cc559c27d6acd98d4d35defe7d4e
def words (linegen):
    for line in linegen:
        a = line.split ('#', 1)[0].strip ().split ()
        if not len (a):
            continue
        yield a


def pathwords (path, noexistok=False, **kwargs):
    try:
        with open (path, **kwargs) as f:
            for line in f:
                a = line.split ('#', 1)[0].strip ().split ()
                if not len (a):
                    continue
                yield a
    except IOError as e:
        if e.errno != 2 or not noexistok:
            raise


def pathtext (path, noexistok=False, **kwargs):
    try:
        with open (path, **kwargs) as f:
            for line in f:
                yield line
    except IOError as e:
        if e.errno != 2 or not noexistok:
            raise
## end

if len (sys.argv) != 4:
    print >>sys.stderr, 'Usage: box-fitpoint <boxfile> <image> <boxnum>'
    sys.exit (1)

boxfn = sys.argv[1]
img = miriad.ImData (sys.argv[2])
boxnum = int (sys.argv[3])

if not img.exists:
    print >>sys.stderr, 'Error: no such image dataset %s' % img
    sys.exit (1)

boxi = 1
boxinfo = None

for a in pathwords (boxfn):
    a = map (float, a)

    if boxi == boxnum:
        boxinfo = a
        break
    boxi += 1

if boxinfo is None:
    print >>sys.stderr, 'Error: no such box #%d (1-based) in %s' % (boxnum, boxfn)
    sys.exit (1)

cra, cdec, wra, wdec = boxinfo
t = mirexec.TaskImFit (in_=img, object='point')
# Note: double-sizing the box.
t.region = 'arcsec,b(%.0f,%.0f,%.0f,%.0f)' % (cra - wra, cdec - wdec, 
                                              cra + wra, cdec + wdec)
t.spar = '1,%.0f,%.0f' % (cra, cdec)
t.run ()
sys.exit (0)
