#! /usr/bin/env python

"""= gpunity - keep delays but set gains to 1+0j
& pkgw
: calibration
+
 Edit a dataset to set all of its antenna gains to 1+0j, but do
 not change the delay values. Requires a calibrated visibility
 dataset with a 'gains' item to operate on.

< vis
 Only a single input UV dataset is supported by GPUNITY.
--
"""

import sys, miriad
from mirtask import keys, readgains
from mirtask.util import printBannerGit, checkusage, wrongusage, die

checkusage (__doc__)
IDENT = '$Id$'
banner = printBannerGit ('gpunity', 'keep delays but set gains to 1+0j', IDENT)

# Get args and check for consistency.

ks = keys.KeySpec ()
ks.keyword ('vis', 'f', ' ')
opts = ks.process ()

if opts.vis == ' ':
    wrongusage (__doc__, 'an input file must be given')

# Init gains, check that args make sense given the dataset.

ds = miriad.Data (opts.vis).open ('rw')
gr = readgains.GainsReader (ds)
gr.prep ()
ndata = gr.nfeeds + gr.ntau

if gr.ntau != 1:
    die ('use gpedit if your dataset doesn\'t have delay info')

# Read and edit data. Could no doubt be more efficient.

time, gains = gr.readAll ()
ndata = gr.nfeeds + gr.ntau

for j in xrange (gr.nants):
    o = j * ndata

    for k in xrange (gr.nfeeds):
        gains[:,o + k] = 1.0

# Write them back out.

item = ds.getItem ('gains', 'w')
ofs = 8

for i in xrange (time.size):
    t = time[i]
    g = gains[i]

    item.write (ofs, N.float64, [t])
    ofs += 8
    item.write (ofs, N.complex64, g)
    ofs += 8 * gr.ngains

del item

# Write history and call it a day.

ds.openHistory ()
ds.writeHistory (banner)
ds.logInvocation ('GPUNITY')
ds.closeHistory ()

del ds

sys.exit (0)
