#! /usr/bin/env python
# -*- python -*-

# Execute lwimager, presetting the 'nchan' and 'spwid' keywords to
# select all channels in all spectral windows.

import sys, os.path, pyrap.tables

mspaths = []
kwargs = []

debug = '--debug' in sys.argv
if debug:
    sys.argv.remove ('--debug')

for arg in sys.argv[1:]:
    if '=' in arg or arg[0] == '-':
        kwargs.append (arg)
    else:
        mspaths.append (arg)

if len (mspaths) != 1:
    print >>sys.stderr, 'mfsimager: error: expect exactly one MS argument (arg without "=")'
    sys.exit (1)

t = pyrap.tables.table (os.path.join (mspaths[0], 'SPECTRAL_WINDOW'), ack=False)
nchan = t.getcol ('NUM_CHAN')
t.close ()

kwargs.append ('spwid=' + ','.join (str (x) for x in xrange (nchan.size)))
kwargs.append ('nchan=' + ','.join (str (x) for x in nchan))

args = ['lwimager', 'ms=' + mspaths[0]] + kwargs
# print >>sys.stderr, '+', ' '.join (args)

if debug:
    os.execvp ('gdb', ['gdb', '--args'] + args)
else:
    os.execvp ('lwimager', args)
