#! /usr/bin/env python
# -*- python -*-
# Copyright 2012 Peter Williams
# Licensed under the GNU General Public License version 3 or higher

import sys, pyrap.tables

for mspath in sys.argv[1:]:
    pyrap.tables.removeImagingColumns (mspath)
