#! /usr/bin/env python
# -*- python -*-

"""
msimhack <input image> <output CASA image>

Copy the contents of an image into a CASA image. It's up to you
to ensure that all of the metadata, etc, are consistent (or not).
"""

import astimage
from mirtask import util


def mirhack (inpath, outpath):
    from pyrap.images import image

    with astimage.open (inpath, 'r') as im:
        indata = im.read ()

    casaout = image (outpath)
    outdata = casaout.get ()

    if indata.size != outdata.size:
        util.die ('cannot import data: input and output have differing '
                  'numbers of pixels')

    outdata[:] = indata.reshape (outdata.shape)
    casaout.put (outdata)

    del casaout # ??? how to close?


def cmdline (argv):
    from os.path import isdir
    util.checkusage (__doc__, argv, usageifnoargs=True)

    if len (argv) != 3:
        util.wrongusage (__doc__, 'exactly 2 arguments expected')

    inpath, outpath = argv[1:]

    if not isdir (outpath):
        util.die ('output "%s" is not a directory', outpath)

    mirhack (inpath, outpath)


if __name__ == '__main__':
    import mirtask.cliutil, sys
    cmdline (sys.argv)
