#! /bin/bash
# -*- shell-script -*-
# Copyright 2012 Peter Williams
# Licensed under the GNU General Public License version 3 or higher

# This is pretty sad.

if tty >/dev/null ; then
    pager=${PAGER:-less -S}
else
    pager=cat
fi

casa-python /dev/fd/0 $1 <<'EOF' 2>&1 |sed -e 's/^.*ms::summary+*.//' |$pager
import sys, casautil
log = casautil.logger ('info')
ms = casautil.tools.ms ()
ms.open (sys.argv[1])
ms.summary (verbose=True)
ms.close ()
EOF
