#! /usr/bin/env casa-python
# -*- python -*-
# Copyright 2012 Peter Williams
# Licensed under the GNU General Public License version 3 or higher

import sys, casac

weightonly = '-w' in sys.argv
if weightonly:
    sys.argv.remove ('-w')

IMAGING_COL_TEMPLATE = {'_c_order': True,
                        'comment': '',
                        'dataManagerGroup': '',
                        'dataManagerType': '',
                        'keywords': {},
                        'maxlen': 0,
                        'ndim': 1,
                        'option': 0,
                        'shape': None,
                        'valueType': 'float'}
IMAGING_DMINFO_TEMPLATE = {'TYPE': 'TiledShapeStMan',
                           'SPEC': {'DEFAULTTILESHAPE': [32, 128]},
                           'NAME': 'imagingweight'}

tb = casac.homefinder.find_home_by_name ('tableHome').create ()
cb = casac.homefinder.find_home_by_name ('calibraterHome').create ()

for mspath in sys.argv[1:]:
    # cb.open() will create the tables if they're not present, so
    # if that's the case, we don't actually need to run initcalset()

    tb.open (mspath, nomodify=False)
    colnames = tb.colnames ()
    needinit = 'MODEL_DATA' in colnames or 'CORRECTED_DATA' in colnames

    if 'IMAGING_WEIGHT' not in colnames:
        c = dict (IMAGING_COL_TEMPLATE)
        c['shape'] = tb.getcell ('DATA', 0).shape[-1:]
        tb.addcols ({'IMAGING_WEIGHT': c}, IMAGING_DMINFO_TEMPLATE)
    tb.close ()

    if not weightonly:
        cb.open (mspath)
        if needinit:
            cb.initcalset ()
        cb.close ()
