#! /bin/sh
# Copyright 2012 Peter Williams
# Licensed under the GNU General Public License version 3 or higher
# Execute uvflag with some standard defaults
exec mirargmerge uvflag flagval=f +noquery "$@"
