#! /bin/sh
# Copyright 2012 Peter Williams
# Licensed under the GNU General Public License version 3 or higher
#
# Display an image

exec mirargmerge -p -r -din cgdisp device=1/xs +wedge,full beamtyp=b,l labtyp=arcsec,arcsec "$@"
