#! /bin/sh
# Copyright 2012 Peter Williams
# Licensed under the GNU General Public License version 3 or higher
#
# 'uvsort' datasest in-place, by moving their current incarnations
# to {basename}.presort

set -e
set -x

for vis in "$@" ; do
    mv "$vis" "$vis".presort
    uvsort vis="$vis".presort out="$vis"
done
