#! /bin/sh
# Copyright 2012 Peter Williams
# Licensed under the GNU General Public License version 3 or higher
#
# Plot phase vs uv distance

exec mirargmerge uvplt device=1/xs +source,nobase nxy=1,1 axis=uvd,ph \
    select='pol(xx,yy),-auto' "$@"
