#! /bin/bash
# -*- shell-script -*-
#
# Companion to uvlock. Revert a UV dataset to its pre-uvlocked
# state.

while [ $# -gt 0 ] ; do
    uv="$1"
    shift

    if [ ! -d "$uv" ] ; then
	echo "$uv is not a directory" >&2
	exit 1
    fi

    for f in "$uv"/* ; do
	case $f in
	    *.orig) continue ;;
	    "$uv/visdata") continue ;;
	esac

	# If there is a backup, restore it. If not,
	# this is some new file: trash it.

	rm -rf "$f"

	if [ -f "$f.orig" ] ; then
	    cp -p "$f.orig" "$f"
	    chmod 644 "$f"
	fi
    done
done

exit 0

