#! /bin/bash
#
# Copy calibrations from the specified cal source to
# other ones

. common.sh

for vis in `./filter-list.py ep.list "$@"` ; do
    src=`cat $vis/ws-src`
    freq=`cat $vis/ws-freq`
    pol=`cat $vis/ws-pol`
    epoch=`cat $vis/ws-epoch`

    [ $src = $cal ] && continue

    echo $vis ...

    # Copy bandpass and meaningless ant gains
    # generated by smamfcal
    shhcmd gpcopy vis=$cal-$freq-$pol-$epoch out=$vis

    # UVcat to precisely mirror sc.sh
    sc="${vis}.sc"
    rm -rf $sc
    shhcmd uvcat vis=$vis out=$sc options=unflagged
    cp $vis/ws-* $sc
    echo $sc >>sc.list

    # Copy meaningful ant gains generated 
    # by mselfcal

    shhcmd gpcopy vis=$cal-$freq-$pol-$epoch.sc out=$sc
done
