#! /bin/bash
#
# Copy calibrations from the specified cal source to
# other ones

. common.sh

for vis in `./filter-list.py fx.list "$@"` ; do
    src=`cat $vis/ws-src`
    freq=`cat $vis/ws-freq`
    pol=`cat $vis/ws-pol`

    [ $src = $cal ] && continue

    echo $vis ...

    # Copy bandpass and meaningless ant gains
    # generated by smamfcal
    shhcmd gpcopy vis=$cal-$freq-$pol out=$vis

    # UVcat to precisely mirror sc.sh
    mf="${vis}.mf"
    rm -rf mf
    shhcmd uvcat vis=$vis out=$mf options=unflagged
    cp $vis/ws-* $mf
    echo $mf >>mf.list

    # Copy meaningful ant gains generated 
    # by mselfcal

    shhcmd gpcopy vis=$cal-$freq-$pol.mf out=$mf
done
