#
# $Id$
#

require 'rubygems'
require 'rake/gempackagetask'

spec = Gem::Specification.new do |s|
  # Basics
  s.name = 'astroutil'
  # Version is YYYY.M.V, where YYYY.M is year and month (1 or 7) of most recent
  # leap second included, and V is version within that epoch.
  s.version = '2009.1.5'
  s.summary = 'Astronomy related extensions for Ruby'
  s.description = <<-EOD
    Provides astronomy related extensions to standard Ruby classes, including
    angle converion methods to Math module and Numeric class, sexagesimal
    conversions to Numeric, Array, and String classes, DateTime::J2000 constant
    for J2000.0 epoch, convenience methods to create DateTime objects from ajd
    and amjd values, and conversions between various time frames to DateTime
    class.  The version number of this gem is YYYY.M.V, where YYYY.M is year
    and month of most recent leap second included, and V is version within that
    epoch.
    EOD
  #s.platform = Gem::Platform::Ruby
  s.required_ruby_version = '>= 1.8.1'
  #s.add_dependency('narray', '>= 0.5.9')

  # About
  s.authors = 'David MacMahon'
  s.email = 'davidm@astro.berkeley.edu'
  s.homepage = 'http://astroutil.rubyforge.org/'
  s.rubyforge_project = 'astroutil' 

  # Files, Libraries, and Extensions
  s.files = FileList[
    'Rakefile',
    'lib/astroutil.rb',
    'test/**/*'
  ]
  s.require_paths = ['lib']
  #s.autorequire = nil
  #s.bindir = 'bin'
  #s.executables = []
  #s.default_executable = nil

  # C compilation
  #s.extensions = %w[ ext/extconf.rb ]

  # Documentation
  #s.rdoc_options = []
  s.has_rdoc = true
  #s.extra_rdoc_files = []

  # Testing TODO
  #s.test_files = [test/test.rb]
end

Rake::GemPackageTask.new(spec) do |pkg|
  pkg.need_zip = true
  pkg.need_tar = true
end
