#!/bin/bash -ex

arch="$(uname -s)/$(uname -i 2>/dev/null || uname -p)"

if [ -e "$arch/naptr.rb" ]
then
  echo "local build for $arch already exists"
else
  mkdir -p "$arch"
  ruby extconf.rb
  make
  cp -p naptr.rb "$arch"
  mv naptr.[sd]* "$arch"
  make distclean
fi
