require 'rubygems'
require 'rake/gempackagetask'

spec = Gem::Specification.new do |s|
  # Basics
  s.name = 'naptr'
  s.version = '0.1.3'
  s.summary = 'Adds pointer access to NArray'
  s.description = 'Extends NArray class with a #ptr method to access underlying pointer'
  #s.platform = Gem::Platform::Ruby
  s.required_ruby_version = '>= 1.8.1'
  s.add_dependency('narray', '>= 0.5.9')

  # About
  s.authors = 'David MacMahon'
  s.email = 'davidm@astro.berkeley.edu'
  s.homepage = 'http://naptr.rubyforge.org/'
  s.rubyforge_project = 'naptr' 

  # Files, Libraries, and Extensions
  s.files = %w[
    Rakefile
    extconf.rb
    naptr.c
    naptr.rb
  ]
  s.require_paths = ['.']
  #s.autorequire = nil
  #s.bindir = 'bin'
  #s.executables = []
  #s.default_executable = nil

  # C compilation
  s.extensions = %w[ extconf.rb ]

  # Documentation TODO
  #s.rdoc_options = []
  #s.has_rdoc = false
  #s.extra_rdoc_files = []

  # Testing TODO
  #s.test_files = []
end

Rake::GemPackageTask.new(spec) do |pkg|
  pkg.need_zip = true
  pkg.need_tar = true
end
