void keyfin_c();
void keyini_c(int, char **);
int keyprsnt_c(const char *);
void bug_c(char, char *);
void keya_c(const char *, char *, const char *);
void keyf_c(const char *, char *, const char *);
void keyd_c(const char *, double *, double);
void keyr_c(const char *, float *, float);
void keyi_c(const char *, int *, int);
void keyl_c(const char *, int *, int);
void mkeyd_c(const char *, double, int, int *);
void scrclose_c(int);
void uvopen_c(int *, char *, char *);
void uvclose_c(int);
void rdhda_c(int,char *,char *, char *, int);
void uvrdvr_c(int, int, char *, char *, char *, int);
void uvinfo_c(int,char *,double *);
void xyopen_c(int *, char *, char *, int, int[]);
void xyclose_c(int);
void hisopen_c(int, char *);
void hiswrite_c(int, char *);
void hisclose_c(int);
void scrread_c(int, float *, int, int);
void haccess_c(int, int *, char *, char *, int *);
void wrhdd_c(int, char *, double);
void wrhdi_c(int, char *, int);
