#! /bin/bash
# Copyright 2013 Peter Williams
# Licensed under the GNU General Public License version 3 or higher

events="$1"
shift
srcreg="$1"
shift
bgreg="$1"
shift

if [ -z "$bgreg" ] ; then
    echo >&2 "usage: xbgband <events.fits> <src.reg> <bg.reg> [energy bin borders (eV)...]

Prints table of: band(eV), expected background counts, total counts, total - background,
 log10(probability that all counts are from background)
"
    exit 1
fi

prevenergy=""

srcarea=$(dmlist "$events[sky=region($srcreg)]" subspace |grep area |tail -n1 |awk '{print $NF}')
bgarea=$(dmlist "$events[sky=region($bgreg)]" subspace |grep area |tail -n1 |awk '{print $NF}')
ascale=$(python -c "print 1. * $srcarea / $bgarea")

function doband () {
    # $1 - energy specification

    bgct=$(dmstat "$events[sky=region($bgreg)][energy=$1][cols energy]" 2>/dev/null \
	|grep good: |awk '{print $NF}')
    srcct=$(dmstat "$events[sky=region($srcreg)][energy=$1][cols energy]" 2>/dev/null \
	|grep good: |awk '{print $NF}')
    bgsc=$(python -c "print $ascale * $bgct")
    subbed=$(python -c "print $srcct - $bgsc")
    pbg=$(python -c "
from math import exp, factorial, log10
b=$bgsc
s=$srcct
print log10(b**s*exp(-b)/factorial(s))")

    printf '%20s\t%.2f\t%d\t%.2f\t%.2f\n' "$1" "$bgsc" "$srcct" "$subbed" "$pbg"
}

while [ $# -gt 0 ] ; do
    curenergy="$1"
    shift
    doband "$prevenergy:$curenergy"
    prevenergy="$curenergy"
done

doband "$prevenergy:"
