#
# $Id$
#

require 'rubygems'
require 'rake/gempackagetask'

spec = Gem::Specification.new do |s|
  # Basics
  s.name = 'pgplotter'
  s.version = '0.0.3'
  s.summary = 'Provides a plotter wrapper around PGPLOT routines'
  s.description = <<-EOD
    Provides a higher level API into the PGPLOT routines.
    EOD
  #s.platform = Gem::Platform::Ruby
  s.required_ruby_version = '>= 1.8.1'
  s.add_dependency('pgplot', '>= 0.1.3')

  # About
  s.authors = 'David MacMahon'
  s.email = 'davidm@astro.berkeley.edu'
  s.homepage = 'http://pgplot.rubyforge.org/'
  s.rubyforge_project = 'pgplot' 

  # Files, Libraries, and Extensions
  s.files = FileList[
    'Rakefile',
    'lib/pgplot/plotter.rb',
  ]
  s.require_paths = ['lib']
  #s.autorequire = nil
  #s.bindir = 'bin'
  #s.executables = []
  #s.default_executable = nil

  # C compilation
  #s.extensions = %w[ ext/extconf.rb ]

  # Documentation TODO
  #s.rdoc_options = []
  #s.has_rdoc = false
  #s.extra_rdoc_files = []

  # Testing TODO
  #s.test_files = [test/test_mirdl.rb]
end

Rake::GemPackageTask.new(spec) do |pkg|
  pkg.need_zip = true
  pkg.need_tar = true
end
