#! /usr/bin/env python
# -*- python -*-
#
# Merge multiple tables of gain uncertainties into one table with many columns

import sys

data = {}
idx = 0

for tabfn in sys.argv[1:]:
    for l in file (tabfn, 'r'):
        a = l.strip ().split ()
        assert len (a) == 6, 'Unexpected table format'

        antpol = (int (a[0]), a[1])
        vals = map (float, a[2:])

        if antpol in data:
            byidx = data[antpol]
        else:
            byidx = data[antpol] = {}

        byidx[idx] = vals
    idx += 1

nfiles = idx

for antpol in sorted (data.iterkeys ()):
    byidx = data[antpol]

    for i in xrange (nfiles):
        if i not in byidx:
            byidx[i] = [None, None, None, None]

    names = ['amp', 'aerr', 'ph', 'perr']

    for qidx in xrange (4):
        print antpol[0], antpol[1], names[qidx],

        for i in xrange (nfiles):
            if byidx[i][qidx] is None:
                print '-',
            else:
                print '%.8g' % byidx[i][qidx],

        print
