#! /bin/tcsh -f
#
# Run a 2D gaussian fit on the relative antenna gains, recording the results.

# Make sure the shell environment is set up
source `dirname $0`/hex-lib-checkenv

if ($#argv < 2) then
    set analysisdir = .
else
    set analysisdir = "$1"
endif

hex-lib-gaussfit $analysisdir >$analysisdir/data-gaussfits.txt
