#! /bin/tcsh -f
#
# Generate coords for a 13-pointing nested hexagonal observation. The inner hexagon is at the
# half-power point and the outer hexagon is at 1.5 times that distance.

set hpcoords = (`hex-lib-calchex7 1.0 $argv`)
set hpra = (${hpcoords[1-7]})
set hpdec = (${hpcoords[8-14]})

# "less power" point. These names are terrible ...
set lpcoords = (`hex-lib-calchex7 1.5 $argv`)
set lpra = (${lpcoords[2-7]}) # skip second center pointing
set lpdec = (${lpcoords[9-14]})

echo $hpra $lpra $hpdec $lpdec
