# $Id$

require 'rubygems'
require 'rake/gempackagetask'

spec = Gem::Specification.new do |s|
  # Basics
  s.name = 'novas'
  s.version = '2.0.1.1'
  s.summary = 'Ruby interface to NOVAS'
  s.description = <<-EOS
    The NOVAS-Ruby package...

    1. Makes NOVAS routines accessible from Ruby.

    2. Makes Ruby usable with NOVAS routines by adding convenience,
       utility, and astronomy related methods to Ruby classes.
    EOS

  #s.platform = Gem::Platform::Ruby
  s.required_ruby_version = '>= 1.8.4'
  #s.requirements << 'a prerequisite'
  #s.add_dependency('narray', '>= 0.5.9')

  # About
  s.authors = 'NOVAS: George H. Kaplan, USNO; Gemification: David MacMahon, UCB RAL'
  s.email = 'davidm@rubyforge.org'
  s.homepage = 'http://novas.rubyforge.org/'
  s.rubyforge_project = 'novas' 

  # Files, Libraries, and Extensions
  s.files = FileList[
    'README.rdoc',
    'Rakefile',
    'lib/novas.rb',
    'ext/*.c',
    'ext/*.h',
    'ext/extconf.rb',
    'ext/novas-c201/*'
  ].to_a
  s.require_paths = ['lib', 'ext']
  #s.autorequire = nil
  #s.bindir = 'bin'
  #s.executables = []
  #s.default_executable = nil

  # C compilation
  s.extensions << 'ext/extconf.rb'

  # Documentation
  s.has_rdoc = true
  s.rdoc_options = %w[-S -x ext/novas-c201/.* -m README.rdoc -t NOVAS-Ruby\ Documentation -x ext/Makefile]
  s.extra_rdoc_files = %w[README.rdoc ext/rb_novas.c ext/rb_body.c ext/rb_cat_entry.c ext/rb_site_info.c]

  # Testing TODO
  s.test_files = ['test/checkout-st.rb']
end

task "pkg" #=> :swig

Rake::GemPackageTask.new(spec) do |pkg|
  pkg.need_zip = true
  pkg.need_tar = true
end
