#! /usr/bin/env python

import sys, miriad, ndshow, numpy as N
from mirtask import util

if len (sys.argv) < 3:
    util.die ('usage: blink <image1> <image2> [...]')

def load (path):
    h = miriad.ImData (path).open ('rw')
    data = h.readPlane (axes=[], topIsZero=True)
    h.close ()
    return data

images = [load (p) for p in sys.argv[1:]]

jointmask = images[0].mask
for im in images[1:]:
    N.logical_or (jointmask, im.mask, jointmask)

for im in images:
    im.mask = jointmask

ndshow.cycle (images)
