#! /usr/bin/env python

import sys, miriad, ndshow
from mirtask import util

if len (sys.argv) != 2:
    util.die ('usage: pwshow <image>')

h = miriad.ImData (sys.argv[1]).open ('rw')
data = h.readPlane (axes=[], topIsZero=True)
h.close ()

ndshow.view (data)
