#!/usr/bin/env tcsh

if $#argv != 1 then
   echo 'wtf?  give me file root.'
   exit(1)
endif

set file = $argv[1]

latex ${file}
#bibtex ${file}
#latex ${file}
latex ${file}
dvips ${file}.dvi  -o ${file}.ps -t letter
ps2pdf ${file}.ps
