#! /usr/bin/tcsh -f

#if !(`pgrep compass`) then
#    compass < /dev/null >& /dev/null &
#endif

while !(-e /ataarchive/scratch/obs/compass/view/mapcmd)
    sleep 10
end

set placeholder = `mktemp XXXXXXXX`
rm -rf $placeholder

review:

cd /ataarchive/scratch/obs/compass/view/

if !(-e $placeholder || -e hold) then
    touch hold
    touch $placeholder
    source mapcmd >& /dev/null
    wip -d 2/xs wip.jypkstat >& /dev/null
    wip -d 3/xs wip.prsv >& /dev/null
    wip -d 4/xs wip.hardstat >& /dev/null
    rm -rf hold
else
    echo "Waiting for update..."
    sleep 60
endif

goto review

exit 0
