#! /usr/bin/tcsh -f
# Calibrator Observing and Measurement Processing 
#         for Array Statistics and Status       
#
# This is going to be the cal observation program. Put simply, it will be
# awesome. Oh yes, it WILL be awesome.

set datapath = /home/obs/mmm/karto/cals
set corr = $1
set stem = compass

mkdir -p /ataarchive/scratch/obs/compass/$corr/view
mkdir -p /ataarchive/scratch/obs/compass/$corr/data

restart:

while (! -e ~/karto/$stem.$corr)
    sleep 10
end

sleep .01

set list = (`cat ~/karto/$stem.$corr`)
rm -rf ~/karto/$stem.$corr
echo COMPASS `date`: "beginning processing of the following entry:"
echo $list

if ($#list < 5) then
    echo COMPASS `date`: "entry seems to be in wrong format; giving up on this scan."
    goto restart
endif

shift list

~/mmm/cshcal/compass.autoflag $corr $list &
~/mmm/cshcal/compass.newrfisweep $corr $list
wait
goto restart
